### ISSUE TITLE
Small inaccuracy in Unide specification

### ISSUE THREAD

**Issue by ChristianRinn** [eclipse/unide#1]
While working on a simple PPMP application in Go, I realized that the 
specification at http://www.eclipse.org/unide/specification/#__time
has a small inaccuracy. The spec says that the array of time offsets ("$_time") 
is optional ("Required: no").
To me this does not make sense because without the time offsets you can not 
have any values referenced to the timestamp and thus the whole series object 
is useless. Furthermore the UML diagram for MeasurementPayload marks the 
$_time-Field as required and I assume that this is correct.

By the way: I first tried to send this directly via e-mail to unide-inbox@eclipse.org but my mail got rejected with the notice "Recipient address rejected: User unknown in local recipient table".

Edit:
Found one more thing: All "limits" fields are obviously of type "number" but the UML diagram says they were strings.

Edit 2:
One more minor thing: The example for the "series" field
`"series": {
  "$_time": [0, 22, 24, 27],
  "temperature": [33, 34, 33, 32],
  "pressure": [1, 1.001. 2.52. 3.2]
}`
is not valid JSON because the dots in the pressure array which separate the values should obviously be commas.

**Comment by ameinhardt** [comment]
Hi @ChristianRinn,
good observations! Indead, the $_time field was a long discussion, since we wanted to support other relations (force-displacement etc.) that you can find in process quality monitoring as well. Nevertheless, I think such scenarios would maybe be better addressed by a separate process interface. Then, we can include process steps, phases and so on.

So I agree with both of your findings: for this purpose, we'll make $_time mandatory and fix the dots in the array.
Thanks,
Axel
